= Terms of Reference for the CF Committee and Governance Panel
12 July 2019

This document was written by Jonathan Gregory in order to capture discussions taking place here:
https://docs.google.com/document/d/1H9E1HKUzgmppLe091aVrHDeEbkPZXEML7_BUSc9Ddxs/edit#heading=h.9v0m7do0ci2e

I haven't reviewed it yet but it is a good idea to track our discussions in that way and discuss them in a PR.


=== Changes made in this document with respect to the http://www.met.rdg.ac.uk/~jonathan/CF_metadata/constitution_original.adoc[original version of 2006]

* State the purpose of these governance rules and the role of the community.
* Include the annual meeting.
* Don't specify the number of members of the committee, but state how it
is to be defined.
* Combine the two committees.
* Remove the rules for modifications, since they are maintained elsewhere,
but state that the committee looks after them.
* Move some items from the constitution of the committee to its terms of reference.


=== CF is a community standard

The CF metadata standard is designed to benefit its user community.  The
community at large is invited to contribute to the development of the
conventions and the standard names by participating in online discussions,
attending meetings, proposing changes, or taking part in any other way they
deem appropriate and useful. Community members participate on a best-effort
basis and have no responsibility to fulfil. The governance arrangements
described in this document are intended to organise and facilitate the
work of the CF community.

=== Constitution of the CF Governance Panel

The CF Governance Panel governs the development and maintenance of the CF
standard on behalf of the user community, under the auspices of the WMO/WCRP
Working Group on Coupled Modelling (WGCM). If the WGCM wishes to transfer or
share responsibility for CF with another permanent committee of an
international organisation, it may decide to do so with the agreement of the CF
Governance Panel and the CF committee.

The panel will include, but not be limited to, members of the WGCM, the leaders
or their nominees of organisations contributing significant resources in
support of CF, and the chair of the CF committee.


=== Terms of reference of the CF Governance Panel

The panel will be responsible for the stewardship of CF, but will not have any
special responsibility for or influence on the technical content of CF.

The panel will ensure that its own constitution and terms of reference, those
of the CF committee, and the aims and general principles of design of the CF
standard are published. These may be altered by the panel only after
appropriate public debate and with the agreement of the CF committee.

The panel will promote and help integrate the use of CF across WCRP programmes,
the broader programmes of WCRP's sponsors (ICSU, WMO, and IOC), and other
interested communities. In particular the panel will attempt to influence
developing metadata standards of WMO and other international organisations so
that they accommodate the CF standard.

The panel will encourage continued support of CF by benevolent organisations
and explore additional funding mechanisms if necessary.

The panel will appoint people who have nominated themselves or agreed to serve
as members of the CF committee. In doing so it will have regard to the
expertise and interests relevant to the remit the committee and will attempt to
obtain representation of a variety of communities and a geographical spread of
members. The maximum and minimum numbers of members of the committee is
decided by agreement between the committee and the panel. The panel will ensure
that the current membership of the committee is published.

The panel will convene an annual meeting of the CF community.


=== Constitution of the CF committee

Anyone with sufficient time, interest and expertise is qualified to serve as an
ordinary member of the CF committee.  Prospective ordinary members should
nominate themselves to the CF panel. Committee members judged by the panel to
have been inactive for an extended period will be asked to resign. Members may
choose to resign at any time and must retire after five years, but may be
reappointed.

The committee will elect its own chair from among its ordinary members whenever
the position becomes vacant.  The chair of the committee may resign the office
at any time and must retire after three years, but may be reelected.

The committee has authority and responsibility for the CF standard, as detailed
in its terms of reference, having regard to the aims and general principles of
design of CF.

The committee will be assisted in its responsibility by two permanent and
funded members of staff, who will be appointed in a manner decided by the CF
Governance Panel, and who will be ex-officio members and secretaries of the
committee. The manager of CF conventions will be the secretary for the
conventions and the manager of CF standard names will be the secretary for the
standard names committee. The committee will propose priorities for work by its
secretaries.

The committee may not devolve responsibility for the CF standard to other
bodies, but it may encourage the formation of other permanent or temporary
ad-hoc groups to debate issues and propose developments to CF.

The committee may not change its constitution or terms of reference itself,
but may propose changes to be made by the CF Governance Panel.

The membership of the committee should include, but need not be limited to,
representatives of those who maintain widely used software which follows the CF
conventions, especially those which the committee regards as reference
implementations, and representatives of the various scientific user communities
of the CF standard.


=== Terms of reference of the CF committee

The committee will be responsible for the CF conventions constituting the CF
netCDF standard, the definition of CF standard names and of any other aspects
of controlled vocabulary, and the format and maintenance of the standard name
table.

The committee will be responsible for the CF conformance document and for
deciding what CF conformance means.

The committee will have an interest in implementation of CF metadata
conventions corresponding to the CF standard in other file formats and media
apart from netCDF.

The committee will have an interest in working towards interoperability with
other vocabulary maintainers.

The committee will ensure that appropriate means are made available for making
proposals and carrying out debates in a way which is visible and open to
participation by all interested parties, and for retaining a permanent public
record of debates and of any decisions made. 

The committee will ensure that the standard, any supporting documents and
resources, and the procedures for proposing and deciding changes are kept
up-to-date and made publicly available.
