[[anchor]]
Proposal to streamline the CF governance process
------------------------------------------------

TODO: Separate into 2 distinct sections and incorporate content from Jonathan

This document has been prepared primarily by Daniel Lee (EUMETSAT) under collaboration with several colleagues at different organisations and in particular with valuable contributions from the following reviewers:

* Guilherme Castelao (SIO-UCSD)
* David Hassel (NCAS, University of Reading)
* Jonathan Gregory (NCAS, University of Reading)
* Ethan Davis (UCAR)
* Martin Juckes (UKRI STFC)

Their contributions have led to improvements in the proposal; nonetheless this document does not necessarily reflect their opinion.

[[introduction]]
Introduction
------------

This proposal is intended to present a concrete discussion point.
It may be adopted in whole, in part, or not at all.

The following changes are proposed via the following mechanisms:

1.  Incorporate https://github.com/cf-convention/cf-convention.github.io/tree/master/Data/cf-documents/cf-governance[_an updated version_] (to be adopted via pull request) of http://cfconventions.org/Data/cf-documents/cf-governance/cf2_whitepaper_final.html[_"Maintaining and Advancing the CF Standard for Earth System Science Community Data"_] into the http://cfconventions.org/governance.html[_Governance document_]
2.  Move the http://cfconventions.org/governance.html[_Governance document_] into the https://github.com/cf-convention/cf-conventions/[_CF Conventions GitHub repository_]
3.  Move the https://github.com/cf-convention/Conformance[_Conformance document _]into the https://github.com/cf-convention/cf-conventions/[_CF Conventions GitHub repository_]
4.  Incorporate the portions of the following proposal that are adopted by the community into the above documents

The intent behind these steps is to improve the capability of controlling and baselining these texts; the website should remain the first point of entry for new users, and indeed could be updated from GitHub if desired.

This should be coordinated by an ad-hoc project group with named responsible people within 6 months.

[[motivation]]
Motivation
----------

The governance processes within the CF Conventions are fairly well-defined but it seems that much work falls on the shoulders of just a few people. Barriers to participation in the governance process are:

* Lack of clarity concerning roles and the amount of time each role invests in the CF governance process.
This makes it difficult for organisations to commit the time of their personnel.
* Multiplicity of roles and people who occupy them, making it difficult to know who to address in the case that change is needed

This proposal attempts to provide additional clarity to the processes and roles involved in the governance of the CF Conventions so that it is easier to share the workload.

[[meetings-and-releases]]
Meetings and releases
---------------------

An Annual Meeting is held for discussing issues relevant to the CF Conventions.

The CF Conventions are updated, *if needed*, 6 weeks after the Annual Meeting.
The need for an update is determined based on whether changes have passed through the approval process (e.g. been merged into the release branch in GitHub).
Exceptionally, updates can be released if needed for a particular project (as was the case for CMIP6 and CF-1.7).

The release frequency and canonical source of the Standard Name Tables will be recorded.
Based off of historical evidence it seems realistic to plan monthly releases via GitHub.

[[roles-and-responsibilities]]
Roles and responsibilities
--------------------------

The following groups are involved in the CF governance processes:

* CF Governance Panel
* Conventions Committee
* Standard Name Committee
* Ad-hoc project teams
* Community at large

The following sections describe the specific roles of people in these groups.
When additional data is available estimates as to the amount of effort per year in person-days will be added in order to support organisations in allocating people to fulfil these roles.

Each group is composed of:

* A chair, responsible for chairing meetings and communicating on the group's behalf;
* A secretary, responsible for ensuring that meetings are properly minuted, maintaining the documents the group is responsible for, and ensuring that formal rules are adhered to; and
* Other members who contribute to the work of the group.

Each year, in each Panel and Committee, the longest serving member's term ends and, if the membership would thus shrink below the desired number, a new member is elected.
A member can stand for re-election as many times as they like.
Additionally, the Chair and Secretary are elected by vote within the group.
Membership in one group does not preclude membership in others.

Any group member can delegate internal duties as needed.

Contributions to any group involved in the CF governance process are tracked in a dedicated document by the secretary of the relevant group.
Ad-hoc project teams fall in the responsibility of the secretary of the group that created them.

[[cf-governance-panel]]
CF Governance Panel
~~~~~~~~~~~~~~~~~~~

The CF Governance Panel:

* Sets the terms of reference for committees and project teams involved in the governance of the CF Conventions;
* Convenes the Annual Meeting;
* Organises elections of the Committees and Panel;
* Arbitrates in the case of disagreements; and
* Guides the relationship of CF to other activities and representing the Conventions as an institution

The Panel can delegate any responsibility to an appropriate committee or ad-hoc project team as needed.

The CF Governance Panel is composed of a total of 5 members.

[[conventions-committee]]
Conventions Committee
~~~~~~~~~~~~~~~~~~~~~

The Conventions Committee:

* Identifies potentially needed changes to the CF Conventions;
* Moderates discussion of proposed changes to the CF Conventions; and
* Publishes new versions of the CF Conventions as needed.

The Conventions Committee is composed of a total of nine members.

[[standard-name-committee]]
Standard Name Committee
~~~~~~~~~~~~~~~~~~~~~~~

The Standard Names Committee:

* Evaluates proposed standard names; and
* Publishes new versions of the Standard Names as needed.

The Standard Names Committee is composed of a total of nine members.

[[ad-hoc-project-teams]]
Ad-hoc project teams
~~~~~~~~~~~~~~~~~~~~

Ad-hoc project teams can be created by the CF Governance Panel and any of the existing Committees.
They have a specific mandate and scope and are entrusted with completing specific tasks within a limited duration.
There are no limits on their size or membership.
After their defined duration has expired, a project team is dissolved.
If it has not been able to complete all of its tasks, a new ad-hoc project team can be created.

Examples for tasks that might be completed by an ad-hoc project team are:

* Migrating between technical platforms (e.g. Trac to GitHub);
* Upgrading the CF Checker;
* Setting up DOI usage in CF;
* Other tasks as needed.

[[community-at-large]]
Community at large
~~~~~~~~~~~~~~~~~~

The CF Conventions are designed to benefit their user community and the community at large is invited to contribute to the Conventions and the Standard Name Tables by participating in online discussions, attending meetings, proposing changes, or taking part in any other way they deem appropriate and useful.
Community members participate on a best effort basis and have no responsibility to fulfil.

[[changes-to-rules-for-making-changes-to-the-cf-conventions]]
Changes to http://cfconventions.org/rules.html[_Rules for making changes
to the CF Conventions_]
------------------------------------------------------------------------------------------------

__Fig. 1: Model of __http://cfconventions.org/rules.html[_Rules for making changes to the CF Conventions_]_._

The process for making changes to the CF Conventions is described in Figure 1.
It is proposed to streamline this process by making the following changes:

1.  Replace the moderator of discussions on GitHub (currently a "member of the conventions committee, or another suitably qualified person") with a member of the of the Conventions Committee or a volunteer whom they have selected. 
2.  Replace the mandatory 3 week period of silence between the beginning of discussion on GitHub and the summary of the proposal's discussion by a 5 week discussion period with no mandatory silence.
This period can be extended if necessary.
3.  Replace the mandatory 3 week period of silence after the moderator summarises the state of discussion by a 1 week period that can be extended if necessary.
