language: ruby
rvm:
    - 2.6

install:
    - gem install asciidoctor
    - asciidoctor --version
    - gem install --pre asciidoctor-pdf
    - asciidoctor-pdf --version

before_script:
    - git config --global user.email $GIT_EMAIL
    - git config --global user.name $GIT_NAME

script:
    - mkdir build
    # Build Conventions
    - asciidoctor cf-conventions.adoc -D build
    - asciidoctor-pdf -d book cf-conventions.adoc -D build
    # Build conformance document
    - asciidoctor conformance.adoc -D build
    - asciidoctor-pdf -d book conformance.adoc -D build

after_success:
    # Always update the "gh-pages" branch, but tag build goes into
    # tag directory and normal build goes into the root directory.
    - mv images/ images~
    - git fetch origin gh-pages:gh-pages
    - git checkout gh-pages
    - if [[ $TRAVIS_TAG ]]; then
        TARGET_DIR=$TRAVIS_TAG;
      else
        TARGET_DIR='.';
      fi
    - mkdir -p $TARGET_DIR
    - mv images~ $TARGET_DIR/images
    - cp build/cf-conventions.html $TARGET_DIR/
    - cp build/cf-conventions.pdf $TARGET_DIR/
    - cp build/conformance.html $TARGET_DIR/
    - cp build/conformance.pdf $TARGET_DIR/
    - git add $TARGET_DIR/images
    - git add $TARGET_DIR/cf-conventions.html
    - git add $TARGET_DIR/cf-conventions.pdf
    - git add $TARGET_DIR/conformance.html
    - git add $TARGET_DIR/conformance.pdf
    - git add $TARGET_DIR/NFFFFFF-1.0.png
    - if [[ $TRAVIS_TAG ]]; then
        sed s/Latest/$TRAVIS_TAG/ index.html > $TARGET_DIR/index.html;
        git add $TARGET_DIR/index.html;
      fi
    - git commit -m "Auto-generated from ${TRAVIS_REPO_SLUG}@${TRAVIS_COMMIT}"
    - git push https://${GHT_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages >/dev/null 2>&1

branches:
    only:
        - master
        # Build tags such as "v1.6"
        - /^v\d+\.\d+/

env:
    global:
        # Values for cf-conventions-bot/cf-conventions
        - secure: "AduHBhrgWc2XOSXUdCzQ8W7z12iHhQjzZgodVbulftW+Uwn2tGx5bPBc0MrrfPJ0AaoE5e1ZeCGk6ZGYVMnOAQEq95NpTJWuqKtfGFvYVuhbVYQ989ZacSugxEWY8zp2yTulQCQ4iuL/HnSgRVEAlAbkIbrjG8mwgBFeXeyUB9TRn11huw/P9PfOOKOVdxgcYmnYzQSD5DVWreLGag6oXMQ/3o3SJUDGpXToZeO+yQZXnKpjEKKIMey0fkCeDeZbviTKVO1A70iiBk9Zc5WEf8FzyJ/sUDr9qjI3gxp70CPV+32aKzqXoxNclssOFPYDoWBZDs8rYS7OBEgyJvE5At5ZhGAmcLn0UGjCSepruJeDdOEYv3tc3QfKm+ZkqNDOjTaHS3gLqHofXqk6C9ppLRzZSxCDbNP7N1nQ/fGMp3dPMrBlH+GG+BNpsQ+wEFY0G9O2veRKfMZnIz5/Lqn20SUOV/0x2FlgYfm1PUBzuqnkwcc+YSOzKNwf4LpCZhUQVQlGWxTmrq9mcSXxi1KzJ7N67+SDqu4x5xC0VI1yrQBGVATCBJYC7XYIe+sABO2gBM9tkO7FpVSzbNDWCnDAPELvBbB1KZfBpV6MI5F9Qx8c2ExnepeOHRIpvcvDJoQfihX8fGXZYbl/XLLnoHmnPJGA8CexMnBHXGHLF6uxdWI="
        - secure: "d+R5tzKSdhytTnjrIW3oAqEnoiVY1I/pqcfNQDBrHDNE+FuCuaGCvjrQuRCil50SAMiZ0/80aN8t9I7iwY2hCcUGJoyfgzTjPi/x0RytcQR4q5qylJw33L3Va1r7g91Y7Fi78c5rXLqXZf/wqhiyTw4uLfMum0ka8TLGn0U960mD9PO8uhavJNZbUsF4puN2q5s7PWBhayVm6S5WiGpKINH3lhH4aFz5+oEBidtBRHMZtT4w5hmjXpU0nd6CfF9/+reMmTjJnbNGCbtTRN3UodIU2OY7ToeLD73f7aBoIOVS2LSjtyWZzCvWszcH7y2U2HlmIiyUA2/DMAnYKYuxHa4P0R5xpSZWUSMb517/YVRWDrJVcQaoWdB4hYQsSYo6Nv/Hj35vf1E7sXiwZCPzSaEWRes31E5mf22Ug5+5R1GwTv0FZ2BxdJ+EZThVvWkm2Cvb4yrOObCq+jC2Z1iJ/f9P0q7DNKzgePiv5MsMWzNFfJ5nwRG9cRl5tbghnScKFntf2LSMVtmHUFHYty1TgxgePko4hUOD3IB14zv71dJLu07qdRuyjZYOjM/qwGfW+FaEcuNC1DHKU+eJPGP9GJjaf+iCM/FQiYiepuofp5ys7k4yqLLlW/FCWGNIPZEdKt4ZggHAl9rCmUDMZF5gClr9YjrbYtCl8mOVYKCVPUg="
        - secure: "3KygyBd58pedh3zsDMAI8HZY7G5w7Y4ZYDvAERBPoZQmM23XD0Ot8TPUM3RGAVBsAhxwomrVaBJNRaMc9/yr8cvarD+o8G/YfgITNVDsSbXTb6cBkA499bTawDK1ocKDGXUYTwGbaLSV9kLiD/0NXptkFEQFzsNtRwsvUXXHOp+j4UBJutCZKZhD/1OfHxk23JmKhkAgeKcOGJ8F3xv3NPwp5DBJ3z3/l31aVjckft+og0EPARJOFxlLEA3/pKwJpuV4LdvuiWK5slDc+IVMgAmJm+5BlqaluH+zBxMol3/uXL57JX0rNIOTKwXQj6Xy+r1iQMlrazK1qy0Z/xQN5IBGjdu4CaDxhg1Kh0yfkZ+TtnamnjbdXYW1/AJW3kuVDFJAdWdRnuZAI4NIWPJTVDDgDVCnqyzduM2O/q8lqvA2U1eTpTnGcExDJZO3zMCj+/opAj1o00HBdxS7hFhN/phBuARwCz+Vj1hoC6p+jC515X+1mhtuP1ghiGVwrmJTyqY1Xc8xJF6xqqhTKR6SGphgeM8OnHeoJeCBspS1ehJkHm9Z7ENmB+bIV082aw4Ti95v0rdRtUOF4L9UUsPJvq/uwxFVAMYr6nbZM4pd+kko+tQsbUoC6g6N+Zn1vcNFQYDkK1StBESxLQ8SxZXXt+Xbjv1bvT88isyKpXlxAQw="
        - secure: "LpRVpYe0hphtelWP5U5o7GMicgorl1TSwmedPG7Sa0TUvqNQltRXXbkGodxtu7fUKrw+SBp+6CGVmgU5RP+Z+R5xETRxNY0IyA8up4uKKACjWvVi5eLp3fKR2R6I0l1LF2GfAtIgV6K2QQWjwar2zrVeN8hs29eI9HqEWQpwgqDxEnHmHpaL84OIcVtNUJkuiIJRkepOHthLe1N3V+xmqYnjXYjmAyN7yyYC+x8KIxqjJSKRUsOmhJwnwpUw27r9QhsVc033KDz+cSm/hG87gnRTkr3iD4jxArKi9d5Oat9ahip6XxLs7MzDpDbb69KTMpf3y4SARuVJ7GW0Gget3GjqF4Ly0r/TLYp4ztWy6aDPvI13w9PJ2NO+L169Vn8HvtRVB45Hu4svFIjpMow80QC10BqUAmKk/AaxSdwQzkZEFPzvYgTGTJjkBy9Gk5isnNoA1GOz2g2b+NZc/H/TuvkvFZBAT4Bl4I1btr9qnYrp5Hinkz+jkUmhGkxD/K0BBa8Cd+bbj+2HyKjAhRTH8g65nIKmgyO97308BBwKeOl2g8kEil6qYydbqLrM9zVJeyYhyTzDFzsXrqWE8g1PT8kO3+5O2FRrZ6otKbCbRUTlkzw/Wzz9leFpOtqYsh59i8sxq1uGVEH3lrbXvfYkBaHnrxXT6FJw5wdcLLu6lW0="

        # Values for cf-convention/cf-conventions
        - secure: "LuUzq7Lf7k0+MxMvW5G+lkQ8vrp1RIDZwQjtDWlTOB+Pteo0V6Ot2rRM+YbGxAjAErAfwj+H6bbNKwBCV+DRUiBVTS/LVQgwT2szRr8Hq1qaXNx/jjWQy1Gza3ZCmwwgP98BEPTOM3s6FD4/EXPxIKRjVRKhyjbBS7f0LQ2J0Yp/kosi0UEEasVq5TOV1nIEU3OxFzTCPdxU/V0gX3lOHVsWDuZVgY3PIsDmet9U5P3IH9R1l8cPKYIY9sjfsmdzIm4uNZI+TGn3HJJxgcO8eA/jM4OwCGn7qaAkMXJws07dNX816UV7Swb/sWCcoqWReOOK5ZTJzW20jz6Ak9bsCHJ3vOQHC3Aj5yv32j9VwNcHQRKjKPwUrg34rqLnfMxJj2Jkn1R07ysae5LwQm8ykh9vCEq2CTT+ztbbGB+y/I/8xJC3c1NXF2eYvaPuJFoQE1vldfZIhrXjQG+vktcosn4IEzySjy82nfSBr+dfrBc/9vcMGng4sAjn5gV6JskUnJgwbKQFPGz9K0Ej7f4zLSDBCNj+8dNFhFDOcVe+c7QCAcDR5t/VUBQb8HKNMJULh0hPXWOlzRXvijvVolw3iDtxNkde9cPI1zyHn0Iqdf8ulG8yFLhdXTEv5Mnn7WBApo3bGr7wPw5VtJESS/6bDz24V8HXj1KJAQBZ89Vtp6Y="
        - secure: "N5kHtOPwdlVe+iCpnDuuuH5yiUyvOGV+vjXrqzTNYktBkh9zkwNw5i3kseNivv0rTLsQSrKFihbFJzOXzzoT6IblSoicyKCL6rhOxNxytM4+OmBDFzg1rERNDw8q8tz8Wc8WS7j2IqfY/CqMSgf7uaLBd7flMWzG6SzEF3yD50qbLa+cF1PxcyrMBPrHrOFNseEOQdgTZnMMle0v6kEzyC8mTnBj0L6CSvQ+oeKvq8a8ufeCRzeQblueOnuxme1SoIqF/cU6S5levArnX/wG86z/6KY8NyE6wDtkXq4sEs7XdfTHlVCe9rNbYo5H2BUfkCpFjjU8C16EgALzhpZhE16xp6tNmOYXghCSEDYKepflXNsKzFqgn2+HiM64tWPcm+gxj/C8nu90EFkHQ0VgYyiXYIlmqYMq4hi7+/G/xkMWmutu3iwdYXs9l31tdrzwbQT4hzg80S/+YoBJ7iNi+BOhG9NG7rh9dZQkeC0Sd8Qbd8mNbL9d1wpAtoDKO4E6LiIdNCWhSMYtaHWEvzyixXtnasw5XoEZ1ErLRQg3PJI3zSGh5cMt3z//kO5/HB/hPX920EYMiCyXFtnB3adCPJlXItCufuhIYqgwEYNPkaiZN3kCEJ4QZW2dVmZsoH/ocxG9Ow0o3yJNXtfWKwIIEw/w59q7Ar/3lpvOK8BeMA0="
        - secure: "JWl4KcaDP4P/ovFxhE/WD46vn1ZbyrhNyaWGoPlKTzTqMNTjYvApq62ae9Qb1Cge9EorHzziB6EvE79ikx+iX0BQLpNOV13epDj/Hqp96br57FZw/D4fAd6R/m0ja9MyqxlGCJT6bKUP2wnceILGzl+HNtI5/sDYo7mwv3UlA2EbhFjeVn27vbkUZKnJaTnsibfHqHKj42vbbuj3h9YHSJEdpyotHMwSnYsoKrVOS/+bFpctmOJgD2KFAmHaqKAPTBPc0n6mRVPG51O/C7cLsMF+RBuP4wYRUEyYfu0pTWa5qTGneVjCk147SS/6YyW8J9cSqWVZB9N4PPCpQ8tUykbn7N62FU77Ew0fW3ljACd0/fHszJgsFK+Pp5Etquq4oQODPqGMvEGU+BcHkyHiUK+Pd7DF+oNO9thvQ4iK5x1/kCYfWciPGC0XzbO4Ue43Fv9zx+RnSTiNp5hroiFRtkFmTWrlMPt4B5vl4S+n46bstWHN19UWBcZIbEdm/2CyJ12JZcyquRCBSp4e7fI9LwchIQb7+AtMfotztgFu9BGvBE9a56R7nZB0O5aSSRgEm1kFjekyWhFQ6N4MEVrFt1OyjW/9UfS8ZTe32yQxFI0eivjflFme2Szb+6BTEkTI3XSQbLFIJaw0bfCY8G1rt6p7AgjhpIFiSkObS9vd940="
