
[[attribute-appendix]]

[appendix]
== Attributes

All CF attributes are listed here except for those that are used to describe grid mappings. See Appendix F for the grid mapping attributes.

The "Type" values are **S** for string, **N** for numeric, and **D** for the type of the data variable. The "Use" values are **G** for global, **C** for variables containing coordinate data, and **D** for variables containing non-coordinate data. "Links" indicates the location of the attribute"s original definition (first link) and sections where the attribute is discussed in this document (additional links as necessary). .Attributes
[options="header",cols="6,2,2,8,12"]
|===============
|{set:cellbgcolor!}
Attribute
|{set:cellbgcolor!}
Type
|{set:cellbgcolor!}
Use
|{set:cellbgcolor!}
Links
|{set:cellbgcolor!}
Description


|{set:cellbgcolor!}
**`add_offset`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
link:$$http://www.unidata.ucar.edu/netcdf/docs/netcdf.html#Attribute-Conventions$$[NUG (8.1)]
	    , <<packed-data>>
|{set:cellbgcolor!}
If present for a variable, this number is to be added to the data after it is read by an application. If both **`scale_factor`** and **`add_offset`** attributes are present, the data are first scaled before the offset is added.


|{set:cellbgcolor!}
**`ancillary_variables`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
<<ancillary-data>>
|{set:cellbgcolor!}
Identifies a variable that contains closely associated data, e.g., the measurement uncertainties of instrument data.


|{set:cellbgcolor!}
**`axis`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
<<coordinate-types>>
|{set:cellbgcolor!}
Identifies latitude, longitude, vertical, or time axes.


|{set:cellbgcolor!}
**`bounds`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
<<cell-boundaries>>
|{set:cellbgcolor!}
Identifies a boundary variable.


|{set:cellbgcolor!}
**`calendar`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
<<calendar>>
|{set:cellbgcolor!}
Calendar used for encoding time axes.


|{set:cellbgcolor!}
**`cell_measures`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
<<cell-measures>>
|{set:cellbgcolor!}
Identifies variables that contain cell areas or volumes.


|{set:cellbgcolor!}
**`cell_methods`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
<<cell-methods>>, <<climatological-statistics>>
|{set:cellbgcolor!}
Records the method used to derive data that represents cell values.


|{set:cellbgcolor!}
**`cf_role`**
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
<<coordinates-metadata>>
|{set:cellbgcolor!}
Identifies the roles of variables that identify features in discrete sampling geometries


|{set:cellbgcolor!}
**`climatology`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
<<climatological-statistics>>
|{set:cellbgcolor!}
Identifies a climatology variable.


|{set:cellbgcolor!}
**`comment`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
G, D
|{set:cellbgcolor!}
<<description-of-file-contents>>
|{set:cellbgcolor!}
Miscellaneous information about the data or methods used to produce it.


|{set:cellbgcolor!}
**`compress`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
<<compression-by-gathering>>, <<reduced-horizontal-grid>>
|{set:cellbgcolor!}
Records dimensions which have been compressed by gathering.


|{set:cellbgcolor!}
**`Conventions`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
G
|{set:cellbgcolor!}
link:$$http://www.unidata.ucar.edu/netcdf/docs/netcdf.html#Attribute-Conventions$$[NUG (8.1)]
|{set:cellbgcolor!}
Name of the conventions followed by the dataset.


|{set:cellbgcolor!}
**`coordinates`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
<<coordinate-system>>, <<labels>>, <<alternative-coordinates>>
|{set:cellbgcolor!}
Identifies auxiliary coordinate variables, label variables, and alternate coordinate variables.


|{set:cellbgcolor!}
**`_FillValue`**
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
C, D
|{set:cellbgcolor!}
link:$$http://www.unidata.ucar.edu/netcdf/docs/netcdf.html#Attribute-Conventions$$[NUG (8.1)]
|{set:cellbgcolor!}
A value used to represent missing or undefined data.  Not allowed for coordinate data except in the case of auxiliary coordinate varibles in discrete sampling geometries.


|{set:cellbgcolor!}
**`featureType`**
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
G
|{set:cellbgcolor!}
<<featureType>>
|{set:cellbgcolor!}
Specifies the type of discrete sampling geometry to which the data in the file belongs, and implies that all data variables in the file contain collections of features of that type.


|{set:cellbgcolor!}
**`flag_masks`**
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
<<flags>>
|{set:cellbgcolor!}
Provides a list of bit fields expressing Boolean or enumerated flags.


|{set:cellbgcolor!}
**`flag_meanings`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
<<flags>>
|{set:cellbgcolor!}
Use in conjunction with **`flag_values`**  to provide descriptive words or phrases for each flag value. If multi-word phrases are used to describe the flag values, then the words within a phrase should be connected with underscores.


|{set:cellbgcolor!}
**`flag_values`**
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
<<flags>>
|{set:cellbgcolor!}
Provides a list of the flag values. Use in conjunction with **`flag_meanings`**.


|{set:cellbgcolor!}
**`formula_terms`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
<<dimensionless-vertical-coordinate>>
|{set:cellbgcolor!}
Identifies variables that correspond to the terms in a formula.


|{set:cellbgcolor!}
**`grid_mapping`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
<<grid-mappings-and-projections>>
|{set:cellbgcolor!}
Identifies a variable that defines a grid mapping.


|{set:cellbgcolor!}
**`history`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
G
|{set:cellbgcolor!}
link:$$http://www.unidata.ucar.edu/netcdf/docs/netcdf.html#Attribute-Conventions$$[NUG (8.1)]
|{set:cellbgcolor!}
List of the applications that have modified the original data.


|{set:cellbgcolor!}
**`instance_dimension`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
<<representations-features>>
|{set:cellbgcolor!}
An attribute which identifies an index variable and names the instance dimension to which it applies. The index variable indicates that the indexed ragged array representation is being used for a collection of features.


|{set:cellbgcolor!}
**`institution`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
G, D
|{set:cellbgcolor!}
<<description-of-file-contents>>
|{set:cellbgcolor!}
Where the original data was produced.


|{set:cellbgcolor!}
**`leap_month`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
<<calendar>>
|{set:cellbgcolor!}
Specifies which month is lengthened by a day in leap years for a user defined calendar.


|{set:cellbgcolor!}
**`leap_year`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
<<calendar>>
|{set:cellbgcolor!}
Provides an example of a leap year for a user defined calendar. It is assumed that all years that differ from this year by a multiple of four are also leap years.


|{set:cellbgcolor!}
**`long_name`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
C, D
|{set:cellbgcolor!}
link:$$http://www.unidata.ucar.edu/netcdf/docs/netcdf.html#Attribute-Conventions$$[NUG (8.1)]
	    , <<long-name>>
|{set:cellbgcolor!}
A descriptive name that indicates a variable"s content. This name is not standardized.


|{set:cellbgcolor!}
**`missing_value`**
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
C, D
|{set:cellbgcolor!}
<<missing-data>>
|{set:cellbgcolor!}
A value used to represent missing or undefined data (deprecated by the NUG).  Not allowed for coordinate data except in the case of auxiliary coordinate variables in discrete sampling geometries.


|{set:cellbgcolor!}
**`month_lengths`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
<<calendar>>
|{set:cellbgcolor!}
Specifies the length of each month in a non-leap year for a user defined calendar.


|{set:cellbgcolor!}
**`positive`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
C
|{set:cellbgcolor!}
[<<COARDS>>]
|{set:cellbgcolor!}
Direction of increasing vertical coordinate value.


|{set:cellbgcolor!}
**`references`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
G, D
|{set:cellbgcolor!}
<<description-of-file-contents>>
|{set:cellbgcolor!}
References that describe the data or methods used to produce it.


|{set:cellbgcolor!}
**`sample_dimension`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
<<representations-features>>
|{set:cellbgcolor!}
An attribute which identifies a count variable and names the sample dimension to which it applies. The count variable indicates that the contiguous ragged array representation is being used for a collection of features.


|{set:cellbgcolor!}
**`scale_factor`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
link:$$http://www.unidata.ucar.edu/netcdf/docs/netcdf.html#Attribute-Conventions$$[NUG (8.1)]
	    , <<packed-data>>
|{set:cellbgcolor!}
If present for a variable, the data are to be multiplied by this factor after the data are read by an application See also the **`add_offset`** attribute.


|{set:cellbgcolor!}
**`source`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
G, D
|{set:cellbgcolor!}
<<description-of-file-contents>>
|{set:cellbgcolor!}
Method of production of the original data.


|{set:cellbgcolor!}
**`standard_error_multiplier`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}
D
|{set:cellbgcolor!}
<<standard-name-modifiers>>
|{set:cellbgcolor!}
If a data variable with a standard_name modifier of standard_error has this attribute, it indicates that the values are the stated multiple of one standard error.


|{set:cellbgcolor!}
**`standard_name`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
C, D
|{set:cellbgcolor!}
<<standard-name>>
|{set:cellbgcolor!}
A standard name that references a description of a variable"s content in the standard name table.


|{set:cellbgcolor!}
**`title`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
G
|{set:cellbgcolor!}
link:$$http://www.unidata.ucar.edu/netcdf/docs/netcdf.html#Attribute-Conventions$$[NUG (8.1)]
|{set:cellbgcolor!}
Short description of the file contents.


|{set:cellbgcolor!}
**`units`**
|{set:cellbgcolor!}
S
|{set:cellbgcolor!}
C, D
|{set:cellbgcolor!}
link:$$http://www.unidata.ucar.edu/netcdf/docs/netcdf.html#Attribute-Conventions$$[NUG (8.1)]
	    , <<units>>
|{set:cellbgcolor!}
Units of a variable"s content.


|{set:cellbgcolor!}
**`valid_max`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}
C, D
|{set:cellbgcolor!}
link:$$http://www.unidata.ucar.edu/netcdf/docs/netcdf.html#Attribute-Conventions$$[NUG (8.1)]
|{set:cellbgcolor!}
Largest valid value of a variable.


|{set:cellbgcolor!}
**`valid_min`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}
C, D
|{set:cellbgcolor!}
link:$$http://www.unidata.ucar.edu/netcdf/docs/netcdf.html#Attribute-Conventions$$[NUG (8.1)]
|{set:cellbgcolor!}
Smallest valid value of a variable.


|{set:cellbgcolor!}
**`valid_range`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}
C, D
|{set:cellbgcolor!}
link:$$http://www.unidata.ucar.edu/netcdf/docs/netcdf.html#Attribute-Conventions$$[NUG (8.1)]
|{set:cellbgcolor!}
Smallest and largest valid values of a variable.

|===============

 

