
[[standard-name-modifiers]]

[appendix]
== Standard Name Modifiers

In the __Units__ column, __u__ indicates units dimensionally equivalent to those for the unmodified standard name.

.Standard Name Modifiers
[options="header",cols="3,1,10"]
|===============
|{set:cellbgcolor!}
Modifier
|{set:cellbgcolor!}
Units
|{set:cellbgcolor!}
Description

|{set:cellbgcolor!}
`detection_minimum`
|{set:cellbgcolor!}
__u__
|{set:cellbgcolor!}
The smallest data value which is regarded as a detectable signal.

|{set:cellbgcolor!}
`number_of_observations`
|{set:cellbgcolor!}
1
|{set:cellbgcolor!}
The number of discrete observations or measurements from which a data value has been derived.

|{set:cellbgcolor!}
`standard_error`
|{set:cellbgcolor!}
__u__
|{set:cellbgcolor!}
The uncertainty of the data value. The standard error includes both systematic and statistical uncertainty. By default it is assumed that the values supplied are for one standard error. If the values supplied are for some multiple of the standard error, the `standard_error` ancillary variable should have an attribute **`standard_error_multiplier`** stating the multiplication factor.

|{set:cellbgcolor!}
`status_flag`
|{set:cellbgcolor!}

|{set:cellbgcolor!}
Flag values indicating the quality or other status of the data values. The variable 
                should have **`flag_values`** or 
                **`flag_masks`** (or both) and **`flag_meanings`** 
                attributes to show how it should be interpreted (<<flags>>).
|===============
