
[[appendix-grid-mappings, Appendix F, Grid Mappings]]

[appendix]
== Grid Mappings

Each recognized grid mapping is described in one of the sections below. Each section contains: the valid name that is used with the **`grid_mapping_name`** attribute; a list of the specific attributes that may be used to assign values to the mapping's parameters; the standard names used to identify the coordinate variables that contain the mapping's independent variables; and references to the mapping's definition or other information that may help in using the mapping. Since the attributes used to set a mapping's parameters may be shared among several mappings, their definitions are contained in a table in the final section. The attributes which describe the
    ellipsoid and prime meridian may be included, when applicable, with
    any grid mapping. 

We have used the FGDC "Content Standard for Digital Geospatial Metadata" <<FGDC>> as a guide in choosing the values for **`grid_mapping_name`** and the attribute names for the parameters describing map projections.


=== Albers Equal Area


----

grid_mapping_name = albers_conical_equal_area
        
----

__Map parameters:__:: 
* **`standard_parallel`** - There may be 1 or 2 values.


* **`longitude_of_central_meridian`**


* **`latitude_of_projection_origin`**


* **`false_easting`**


* **`false_northing`**

 

__Map coordinates:__:: The x (abscissa) and y (ordinate) rectangular coordinates are identified by the **`standard_name`** attribute values **`projection_x_coordinate`** and **`projection_y_coordinate`** respectively.

__Notes:__:: Notes on using the **`PROJ.4`** software package for computing the mapping may be found at link:$$http://www.remotesensing.org/geotiff/proj_list/albers_equal_area_conic.html$$[http://www.remotesensing.org/geotiff/proj_list/albers_equal_area_conic.html] .


[[azimuthal-equidistant]]

=== Azimuthal equidistant


----

grid_mapping_name = azimuthal_equidistant
        
----

  __Map parameters:__:: 
* **`longitude_of_projection_origin`**


* **`latitude_of_projection_origin`**


* **`false_easting`**


* **`false_northing`**

 

__Map coordinates:__:: The x (abscissa) and y (ordinate) rectangular coordinates are identified by the **`standard_name`** attribute values **`projection_x_coordinate`** and **`projection_y_coordinate`** respectively.

__Notes:__:: Notes on using the **`PROJ.4`** software package for computing the mapping may be found at link:$$http://www.remotesensing.org/geotiff/proj_list/azimuthal_equidistant.html$$[http://www.remotesensing.org/geotiff/proj_list/azimuthal_equidistant.html] .




[[lambert-azimuthal-equal-area]]

=== Lambert azimuthal equal area


----

grid_mapping_name = lambert_azimuthal_equal_area
        
----

  __Map parameters:__:: 
* **`longitude_of_projection_origin`**


* **`latitude_of_projection_origin`**


* **`false_easting`**


* **`false_northing`**

 

__Map coordinates:__:: The x (abscissa) and y (ordinate) rectangular coordinates are identified by the **`standard_name`** attribute values **`projection_x_coordinate`** and **`projection_y_coordinate`** respectively.

__Notes:__:: Notes on using the **`PROJ.4`** software package for computing the mapping may be found at link:$$http://www.remotesensing.org/geotiff/proj_list/lambert_azimuthal_equal_area.html$$[http://www.remotesensing.org/geotiff/proj_list/lambert_azimuthal_equal_area.html] .




=== Lambert conformal


----

grid_mapping_name = lambert_conformal_conic
        
----

  __Map parameters:__:: 
* **`standard_parallel`** - There may be 1 or 2 values.


* **`longitude_of_central_meridian`**


* **`latitude_of_projection_origin`**


* **`false_easting`**


* **`false_northing`**

 

__Map coordinates:__:: The x (abscissa) and y (ordinate) rectangular coordinates are identified by the **`standard_name`** attribute values **`projection_x_coordinate`** and **`projection_y_coordinate`** respectively.

__Notes:__:: Notes on using the **`PROJ.4`** software package for computing the mapping may be found at link:$$http://www.remotesensing.org/geotiff/proj_list/lambert_conic_conformal_2sp.html$$[http://www.remotesensing.org/geotiff/proj_list/lambert_conic_conformal_2sp.html] .




=== Lambert Cylindrical Equal Area


----

grid_mapping_name = lambert_cylindrical_equal_area
      
----

__Map parameters:__:: 
* **`longitude_of_central_meridian`**
* Either **`standard_parallel`** or **`scale_factor_at_projection_origin`**
* **`false_easting`**
* **`false_northing`**
          

__Map coordinates:__:: The x (abscissa) and y (ordinate) rectangular coordinates are identified by the **`standard_name`** attribute value **`projection_x_coordinate`** and **`projection_y_coordinate`** respectively.
          

__Notes:__:: Notes on using the PROJ.4 software packages for computing the mapping may be found at link:$$http://www.remotesensing.org/geotiff/proj_list/cylindrical_equal_area.html$$[http://www.remotesensing.org/geotiff/proj_list/cylindrical_equal_area.html] ("Lambert Cylindrical Equal Area" or EPSG 9834 or EPSG 9835). Detailed formulas can be found in [Snyder] pages 76-85.
          


=== Latitude-Longitude


----

grid_mapping_name = latitude_longitude
      
----

This grid mapping defines the canonical 2D geographical coordinate system based upon latitude and longitude coordinates on a spherical Earth. It is included so that the figure of the Earth can be described.

__Map parameters:__:: None.

__Map coordinates:__:: The rectangular coordinates are longitude and latitude 
identified by the usual conventions 
(<<latitude-coordinate>> and <<longitude-coordinate>>).
          


=== Mercator


----

grid_mapping_name = mercator
      
----

__Map parameters:__:: 
* **`longitude_of_projection_origin`**
* Either **`standard_parallel`** (EPSG 9805) or **`scale_factor_at_projection_origin`** (EPSG 9804)
              
* **`false_easting`**
* **`false_northing`**
          

__Map coordinates:__:: The x (abscissa) and y (ordinate) rectangular coordinates are identified by the **`standard_name`** attribute value **`projection_x_coordinate`** and **`projection_y_coordinate`** respectively.
          

__Notes:__:: Notes on using the PROJ.4 software packages for computing the mapping may be found at link:$$http://www.remotesensing.org/geotiff/proj_list/mercator_1sp.html$$[http://www.remotesensing.org/geotiff/proj_list/mercator_1sp.html] ("Mercator (1SP)" or EPSG 9804) or link:$$http://www.remotesensing.org/geotiff/proj_list/mercator_2sp.html$$[http://www.remotesensing.org/geotiff/proj_list/mercator_2sp.html] ("Mercator (2SP)" or EPSG 9805).
          
+
More information on formulas available in <<OGP-EPSG_GN7_2>>.
          


=== Orthographic


----

grid_mapping_name = orthographic
      
----

__Map parameters:__:: 
* **`longitude_of_projection_origin`**
* **`latitude_of_projection_origin`**
* **`false_easting`**
* **`false_northing`**
          

__Map coordinates:__:: The x (abscissa) and y (ordinate) rectangular coordinates are identified by the **`standard_name`** attribute value **`projection_x_coordinate`** and **`projection_y_coordinate`** respectively.
          

__Notes:__:: Notes on using the PROJ.4 software packages for computing the mapping may be found at link:$$http://www.remotesensing.org/geotiff/proj_list/orthographic.html$$[http://www.remotesensing.org/geotiff/proj_list/orthographic.html] ("Orthographic" or EPSG 9840).
          
+
More information on formulas available in <<OGP-EPSG_GN7_2>>.
          


[[polar-stereographic]]

=== Polar stereographic


----

grid_mapping_name = polar_stereographic
      
----

__Map parameters:__:: 
* **`straight_vertical_longitude_from_pole`**


* **`latitude_of_projection_origin`** - Either +90. or -90.


* Either **`standard_parallel`** or **`scale_factor_at_projection_origin`**


* **`false_easting`**


* **`false_northing`**

 

__Map coordinates:__:: The x (abscissa) and y (ordinate) rectangular coordinates are identified by the **`standard_name`** attribute values **`projection_x_coordinate`** and **`projection_y_coordinate`** respectively.

__Notes:__:: Notes on using the **`PROJ.4`** software package for computing the mapping may be found at link:$$http://www.remotesensing.org/geotiff/proj_list/polar_stereographic.html$$[http://www.remotesensing.org/geotiff/proj_list/polar_stereographic.html] .


=== Rotated pole


----

grid_mapping_name = rotated_latitude_longitude
        
----

  __Map parameters:__:: 
* **`grid_north_pole_latitude`**


* **`grid_north_pole_longitude`**


* **`north_pole_grid_longitude`** - This parameter is option (default is 0).

 

__Map coordinates:__:: The rotated latitude and longitude coordinates are identified by the **`standard_name`** attribute values **`grid_latitude`** and **`grid_longitude`** respectively.

__Notes:__:: 
{nbsp}



=== Stereographic


----

grid_mapping_name = stereographic
        
----

  __Map parameters:__:: 
* **`longitude_of_projection_origin`**


* **`latitude_of_projection_origin`**


* **`scale_factor_at_projection_origin`**


* **`false_easting`**


* **`false_northing`**

 

__Map coordinates:__:: The x (abscissa) and y (ordinate) rectangular coordinates are identified by the **`standard_name`** attribute values **`projection_x_coordinate`** and **`projection_y_coordinate`** respectively.

__Notes:__:: Formulas for the mapping and its inverse along with notes on using the **`PROJ.4`** software package for doing the calcuations may be found at link:$$http://www.remotesensing.org/geotiff/proj_list/stereographic.html$$[http://www.remotesensing.org/geotiff/proj_list/stereographic.html] . See the section "Polar stereographic" for the special case when the projection origin is one of the poles.




=== Transverse Mercator


----

grid_mapping_name = transverse_mercator
        
----

  __Map parameters:__:: 
* **`scale_factor_at_central_meridian`**


* **`longitude_of_central_meridian`**


* **`latitude_of_projection_origin`**


* **`false_easting`**


* **`false_northing`**

 

__Map coordinates:__:: The x (abscissa) and y (ordinate) rectangular coordinates are identified by the **`standard_name`** attribute values **`projection_x_coordinate`** and **`projection_y_coordinate`** respectively.

__Notes:__:: Formulas for the mapping and its inverse along with notes on using the **`PROJ.4`** software package for doing the calcuations may be found at link:$$http://www.remotesensing.org/geotiff/proj_list/transverse_mercator.html$$[http://www.remotesensing.org/geotiff/proj_list/transverse_mercator.html] .




=== Vertical perspective


----

grid_mapping_name = vertical_perspective
      
----

__Map parameters:__:: 
* **`latitude_of_projection_origin`**


* **`longitude_of_projection_origin`**


* **`perspective_point_height`**


* **`false_easting`**


* **`false_northing`**



__Map coordinates:__:: The x (abscissa) and y (ordinate) rectangular coordinates 
are identified by the **`standard_name`** attribute 
            value **`projection_x_coordinate`** and 
            **`projection_y_coordinate`** respectively.
          

__Notes:__:: Notes on using the **`PROJ.4`** software packages 
             for computing the mapping may be found at 
             link:$$http://www.remotesensing.org/geotiff/proj_list/geos.html$$[http://www.remotesensing.org/geotiff/proj_list/geos.html] . These notes assume the point of perspective
             is directly over the equator. A more general description 
             of vertical perspective projection is given in 
             <<Snyder>>, pages 169-181.
           

In the following table the "Type" values are
**S** for string and
         **N** for numeric. 

.Grid Mapping Attributes
[options="header",cols="6,1,16"]
|===============
|{set:cellbgcolor!}
Attribute
|{set:cellbgcolor!}
Type
|{set:cellbgcolor!}
Description


|{set:cellbgcolor!}
**`earth_radius`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            Used to specify the radius, in metres, of the spherical 
            figure used to approximate the shape of the Earth. This 
            attribute should be specified for those projected coordinate 
            reference systems in which the X-Y cartesian coordinates 
            have been derived using a spherical Earth approximation. If 
            the cartesian coordinates were derived using an ellipsoid, 
            this attribute should not be defined. Example: "6371007", 
            which is the radius of the GRS 1980 Authalic Sphere.
            


|{set:cellbgcolor!}
**`false_easting`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            The value added to all abscissa values in the rectangular
            coordinates for a map projection. This value frequently
            is assigned to eliminate negative numbers. Expressed in
            the unit of the coordinate variable identified by the
            standard name **`projection_x_coordinate`**.
            


|{set:cellbgcolor!}
**`false_northing`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            The value added to all ordinate values in the rectangular
            coordinates for a map projection. This value frequently
            is assigned to eliminate negative numbers. Expressed in
            the unit of the coordinate variable identified by the
            standard name **`projection_y_coordinate`**.
        


|{set:cellbgcolor!}
**`grid_mapping_name`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            The name used to identify the grid mapping.
        


|{set:cellbgcolor!}
**`grid_north_pole_latitude`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            True latitude (degrees_north) of the north pole of the rotated grid.
        


|{set:cellbgcolor!}
**`grid_north_pole_longitude`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            True longitude (degrees_east) of the north pole of the rotated grid.
        


|{set:cellbgcolor!}
**`inverse_flattening`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            Used to specify the __inverse__ flattening 
            (__1/f__) of the ellipsoidal figure 
            associated with the geodetic datum and used to approximate the shape 
            of the Earth. The flattening (__f__) of the ellipsoid 
            is related to the semi-major and semi-minor axes by the formula 
            __f = (a-b)/a__. In the case 
            of a spherical Earth this attribute should be omitted or set to zero. 
            Example: 298.257222101 for the GRS 1980 ellipsoid. (Note: By 
            convention the dimensions of an ellipsoid are specified using either 
            the semi-major and semi-minor axis lengths, or the semi-major axis 
            length and the inverse flattening. If all three attributes are 
            specified then the supplied values must be consistent with the 
            aforementioned formula.)
            


|{set:cellbgcolor!}
**`latitude_of_projection_origin`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            The latitude chosen as the origin of rectangular coordinates for a map projection.
            Domain: **`-90.0 &lt;= latitude_of_projection_origin &lt;= 90.0`**


|{set:cellbgcolor!}
**`longitude_of_central_meridian`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            The line of longitude at the center of a map projection generally used as the basis for constructing the projection. 
            Domain: **`-180.0 &lt;= longitude_of_central_meridian &lt; 180.0`**


|{set:cellbgcolor!}
**`longitude_of_prime_meridian`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            Specifies the longitude, with respect to Greenwich, of the prime 
            meridian associated with the geodetic datum. The prime meridian defines 
            the origin from which longitude values are determined. Not to be 
            confused with the projection origin longitude 
            (cf. **`longitude_of_projection_origin`**, a.k.a. central 
            meridian) which defines the longitude of the map projection origin. 
            Domain: **`-180.0 &lt;= longitude_of_prime_meridian &lt; 180.0`** decimal degrees. 
            Default = **`0.0`**


|{set:cellbgcolor!}
**`longitude_of_projection_origin`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            The longitude chosen as the origin of rectangular coordinates for a map projection.
            Domain: **`-180.0 &lt;= longitude_of_projection_origin &lt; 180.0`**


|{set:cellbgcolor!}
**`north_pole_grid_longitude`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            Longitude (degrees) of the true north pole in the rotated grid.
        


|{set:cellbgcolor!}
**`perspective_point_height`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            Records the height, __in metres__, of the map 
            projection perspective point above the ellipsoid (or sphere). Used 
            by perspective-type map projections, for example the Vertical 
            Perspective Projection, which may be used to simulate the view from 
            a Meteosat satellite.
            


|{set:cellbgcolor!}
**`scale_factor_at_central_meridian`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            A multiplier for reducing a distance obtained from a map by
            computation or scaling to the actual distance along the
            central meridian.
            Domain: **`scale_factor_at_central_meridian &gt; 0.0`**


|{set:cellbgcolor!}
**`scale_factor_at_projection_origin`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            A multiplier for reducing a distance obtained from
            a map by computation or scaling to the actual distance
            at the projection origin.
            Domain: **`scale_factor_at_projection_origin &gt; 0.0`**


|{set:cellbgcolor!}
**`semi_major_axis`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            Specifies the length, __in metres__, of the semi-major 
            axis of the ellipsoidal figure associated with the geodetic datum and 
            used to approximate the shape of the Earth. Commonly denoted using the 
            symbol __a__. In the case of a spherical Earth 
            approximation this attribute defines the radius of the Earth. See 
            also the **`inverse_flattening`** attribute.
            


|{set:cellbgcolor!}
**`semi_minor_axis`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            Specifies the length, __in metres__, of the semi-minor 
            axis of the ellipsoidal figure associated with the geodetic datum and 
            used to approximate the shape of the Earth. Commonly denoted using the 
            symbol __b__. In the case of a spherical Earth 
            approximation this attribute should be omitted (the preferred option) 
            or else set equal to the value of the semi_major_axis attribute. See also the inverse_flattening attribute.
            


|{set:cellbgcolor!}
**`standard_parallel`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            Specifies the line, or lines, of latitude at which the developable map 
            projection surface (plane, cone, or cylinder) touches the reference 
            sphere or ellipsoid used to represent the Earth. Since there is zero 
            scale distortion along a standard parallel it is also referred to as 
            a "latitude of true scale". In the situation where a conical 
            developable surface intersects the reference ellipsoid there are two 
            standard parallels, in which case this attribute can be used as a 
            vector to record both latitude values, with the additional convention 
            that the standard parallel nearest the pole (N or S) is provided first. 
            
            
            Domain: **`-90.0 &lt;= standard_parallel &lt;= 90.0`**


|{set:cellbgcolor!}
**`straight_vertical_longitude_from_pole`**
|{set:cellbgcolor!}
N
|{set:cellbgcolor!}

            The longitude to be oriented straight up from the North or South Pole.
            Domain: **`-180.0 &lt;= straight_vertical_longitude_from_pole &lt; 180.0`**

|===============

