= NetCDF Climate and Forecast (CF) Metadata Conventions
Brian Eaton; Jonathan Gregory; Bob Drach; Karl Taylor; Steve Hankin; Jon Blower; John Caron; Rich Signell; Phil Bentley; Greg Rappa; Heinke Höck; Alison Pamment; Martin Juckes; Martin Raspaud
Version 1.7
:sectanchors:
:toc: macro
:toclevels: 3

toc::[]

:numbered!:
include::toc-extra.adoc[]

== About the authors

.Original Authors
* Brian Eaton, NCAR
* Jonathan Gregory, University of Reading and UK Met Office Hadley Centre
* Bob Drach, PCMDI, LLNL
* Karl Taylor, PCMDI, LLNL
* Steve Hankin, PMEL, NOAA

.Additional Authors
* Jon Blower, University of Reading
* John Caron, UCAR
* Rich Signell, USGS
* Phil Bentley, UK Met Office Hadley Centre
* Greg Rappa, MIT
* Heinke Höck, DKRZ
* Alison Pamment, BADC
* Martin Juckes, BADC
* Martin Raspaud, SMHI
* Randy Horne, Excalibur Laboratories, Inc., Melbourne Beach Florida USA
* Timothy Whiteaker, University of Texas
* David Blodgett, USGS

Many others have contributed to the development of CF through their participation in discussions about proposed changes.

[abstract]
== Abstract

This document describes the CF conventions for climate and forecast metadata designed to promote the processing and sharing of files created with the netCDF Application Programmer Interface <<NetCDF>>. The conventions define metadata that provide a definitive description of what the data in each variable represents, and of the spatial and temporal properties of the data. This enables users of data from different sources to decide which quantities are comparable, and facilitates building applications with powerful extraction, regridding, and display capabilities.

The CF conventions generalize and extend the COARDS conventions <<COARDS>>. The extensions include metadata that provides a precise definition of each variable via specification of a standard name, describes the vertical locations corresponding to dimensionless vertical coordinate values, and provides the spatial coordinates of non-rectilinear gridded data. Since climate and forecast data are often not simply representative of points in space/time, other extensions provide for the description of coordinate intervals, multidimensional cells and climatological time coordinates, and indicate how a data value is representative of an interval or cell. This standard also relaxes the COARDS constraints on dimension order and specifies methods for reducing the size of datasets.

:numbered!:
include::pr01.adoc[]

:numbered:
include::ch01.adoc[]

:numbered:
include::ch02.adoc[]

:numbered:
include::ch03.adoc[]

:numbered:
include::ch04.adoc[]

:numbered:
include::ch05.adoc[]

:numbered:
include::ch06.adoc[]

:numbered:
include::ch07.adoc[]

:numbered:
include::ch08.adoc[]

:numbered:
include::ch09.adoc[]

:numbered!:
include::appa.adoc[]

:numbered!:
include::appb.adoc[]

:numbered!:
include::appc.adoc[]

:numbered!:
include::appd.adoc[]

:numbered!:
include::appe.adoc[]

:numbered!:
include::appf.adoc[]

:numbered!:
include::appg.adoc[]

:numbered:
include::apph.adoc[]

:numbered!:
include::history.adoc[]

:numbered!:
include::bibliography.adoc[]
