
==  Labels and Alternative Coordinates 




[[labels, Section 6.1, "Labels"]]
=== Labels





Character strings can be used to provide a name or label for each
element of an axis. This is particularly useful for discrete axes
(section 4.5). For instance, if a data variable contains time series of
observational data from a number of observing stations, it may be
convenient to provide the names of the stations as labels for the
elements of the station dimension (<<time-series-data>>).
There are several other uses for labels in CF. For instance,
<<northward-heat-transport-in-atlantic-ocean-ex>> shows the use of labels
to indicate geographic regions.

Character strings labelling the elements of an axis are regarded as
string-valued auxiliary coordinate variables. The **`coordinates`**
attribute of the data variable names the variable that contains the
string array.
An application processing the variables listed in the **`coordinates`**
attribute can recognize a string-valued auxiliary coordinate variable because
it has a type of **`char`** or **`string`**.
If the variable has a type of **`char`**, the inner dimension (last dimension
in CDL terms) is the maximum length of each string, and the other dimensions
are axis dimensions.
If an auxiliary coordinate variable has a type of **`string`** and has no
dimensions, or has a type of **`char`** and has only one dimension (the maximum
length of the string), it is a string-valued scalar coordinate variable (see
<<scalar-coordinate-variables>>).  
As such, it has the same information content and can be used in the same
contexts as a string-valued auxiliary coordinate variable of a size one
dimension.
This is a convenience feature.


[[geographic-regions, Section 6.1.1, "Geographic Regions"]]
==== Geographic Regions

When data is representative of geographic regions which can be identified by names but which have complex boundaries that cannot practically be specified using longitude and latitude boundary coordinates, a labeled axis should be used to identify the regions. We recommend that the names be chosen from the list of link:$$http://cfconventions.org/Data/cf-standard-names/docs/standardized-region-names.html$$[standardized region names] whenever possible. To indicate that the label values are standardized the variable that contains the labels must be given the **`standard_name`** attribute with the value `region`.

[[northward-heat-transport-in-atlantic-ocean-ex]]
[caption="Example 6.1. "]
.Northward heat transport in Atlantic Ocean
====

Suppose we have data representing northward heat transport across a set of zonal slices in the Atlantic Ocean. Note that the standard names to describe this quantity do not include location information. That is provided by the latitude coordinate and the labeled axis:
----
dimensions:
  times = 20 ;
  lat = 5
  lbl = 1 ;
variables:
  float n_heat_transport(time,lat,lbl);
    n_heat_transport:units="W";
    n_heat_transport:coordinates="geo_region";
    n_heat_transport:standard_name="northward_ocean_heat_transport";
  double time(time) ;
    time:long_name = "time" ;
    time:units = "days since 1990-1-1 0:0:0" ;
  float lat(lat) ;
    lat:long_name = "latitude" ;
    lat:units = "degrees_north" ;
  string geo_region(lbl) ;
    geo_region:standard_name="region"
data:
  geo_region = "atlantic_ocean" ;
  lat = 10., 20., 30., 40., 50. ;
	
----


====




[[alternative-coordinates, Section 6.2, "Alternative Coordinates"]]
=== Alternative Coordinates

In some situations a dimension may have alternative sets of coordinates values. Since there can only be one coordinate variable for the dimension (the variable with the same name as the dimension), any alternative sets of values have to be stored in auxiliary coordinate variables. For such alternative coordinate variables, there are no mandatory attributes, but they may have any of the attributes allowed for coordinate variables.

[[model-level-numbers-ex]]
[caption="Example 6.2. "]
.Model level numbers
====

Levels on a vertical axis may be described by both the physical coordinate and the ordinal model level number.
----
float xwind(sigma,lat);
  xwind:coordinates="model_level";
float sigma(sigma); // physical height coordinate
  sigma:long_name="sigma";
  sigma:positive="down";
int model_level(sigma); // model level number at each height
  model_level:long_name="model level number";
  model_level:positive="up";
      
----


====

