= Terms of Reference for CF Committees and Governance Panel
B. N. Lawrence, R. Drach, B. E. Eaton, J. M. Gregory, S. C. Hankin, R. K. Lowry, R. K. Rew, and K. E. Taylor
From the CF white paper of 2006, Appendix Two: Terms of Reference for Committees and Governance Panel

// TODOs
// Add: What bodies exist? How do they interact? What are their duties? What other things are there to do?
// What are the "responsibilities/duties" of the different stakeholders?
// How do we ensure that there is a moderator who processes a ticket?
// Move tenses: None of this "will be", etc. - this is *what we do now*.
// Rename to Constitution
// Any time it fits better in CONTRIBUTING.md, propose changes there. A lot of the pending changes belong there.
// Don't forget that the website will need updating as well.
// Also: Conformance doc needs to go into Conventions repo. Document such changes in the issue as they transcend the scope of an issue restricted to a repo.
// Food for thought: Who is a member of the cf-conventions GH org? Currently only 4...
// Possible sections to add: a) Meetings and releases; b) Roles and responsibilities
// Examine #150, #151 - is that reflected here?
////
Stuff we know we want to implement in CONTRIBUTING.md
Streamline moderation process by:
1. Replace the moderator of discussions on GitHub (currently a "member of the conventions committee, or another suitably qualified person") with a member of the of the Conventions Committee or a volunteer whom they have selected. 
2. Replace the mandatory 3 week period of silence between the beginning of discussion on GitHub and the summary of the proposal's discussion by a 5 week discussion period with no mandatory silence.
This period can be extended if necessary.
3. Replace the mandatory 3 week period of silence after the moderator summarises the state of discussion by a 1 week period that can be extended if necessary.

Also needed in this document are stuff about moderator's role, etc. and how to assign people
////

== Introduction

The CF Conventions are designed for the benefit of its users.
This constitution sets forth the mechanisms that are used in order to ensure that the Conventions can evolve in order to meet its users' needs.

// TODO: Revise, bring in line with text from Jonathan's ToR sections
== Roles and responsibilities

The following groups are involved in the CF governance processes:

* CF Governance Panel
* Conventions Committee
* Standard Name Committee
* Ad-hoc project teams
* Community at large

The following sections describe the specific roles of people in these groups.
When additional data is available estimates as to the amount of effort per year in person-days will be added in order to support organisations in allocating people to fulfil these roles.

Each group is composed of:

* A chair, responsible for chairing meetings and communicating on the group's behalf;
* A secretary, responsible for ensuring that meetings are properly minuted, maintaining the documents the group is responsible for, and ensuring that formal rules are adhered to; and
* Other members who contribute to the work of the group.

Each year, in each Panel and Committee, the longest serving member's term ends and, if the membership would thus shrink below the desired number, a new member is elected.
A member can stand for re-election as many times as they like.
Additionally, the Chair and Secretary are elected by vote within the group.
Membership in one group does not preclude membership in others.

Any group member can delegate internal duties as needed.

Contributions to any group involved in the CF governance process are tracked in a dedicated document by the secretary of the relevant group.
Ad-hoc project teams fall in the responsibility of the secretary of the group that created them.

=== Constitution of the CF Governance Panel

The CF Governance Panel governs the development and maintenance of the CF standard on behalf of the user community, under the auspices of the WMO/WCRP Working Group on Coupled Modelling (WGCM).
If the WGCM wishes to transfer or share responsibility for CF with another permanent committee of an international organisation, it may decide to do so with the agreement of the CF Governance Panel and the CF committee.

The panel will include, but not be limited to, members of the WGCM, the leaders, or their nominees, of organisations contributing significant resources in support of CF, and the chairs of the CF committees on conventions and standard names.

=== Terms of reference of the CF Governance Panel

The panel will be responsible for the stewardship of CF, but will not have any special responsibility for or influence on the technical content of CF.

The panel will ensure that its own constitution and terms of reference, those of the CF committees, and the aims and general principles of design of the CF standard are published.
These may be altered by the panel only after appropriate public debate and with the agreement of both CF committees.

The panel will promote and help integrate the use of CF across WCRP programmes, the broader programmes of WCRP's sponsors (ICSU, WMO, and IOC), and other interested communities.
In particular the panel will attempt to influence developing metadata standards of WMO and other international organisations so that they accommodate the CF standard.

The panel will encourage continued support of CF by benevolent organisations and explore additional funding mechanisms if necessary.

The panel will appoint people who have nominated themselves or agreed to serve as members of the conventions committee and the standard names committee.
In doing so it will have regard to the expertise and interests relevant to the remit of each committee and will attempt to obtain representation of a variety of communities and a geographical spread of members.
The maximum and minimum numbers of members of either committee is decided by agreement between that committee and the panel.
The panel will ensure that the current membership of the two CF committees is published.

// TODO: Is this really GP, or a CC issue?
The Governance Panel will convene an Annual Meeting of the CF community for discussing issues relevant to the CF Conventions.
The CF Conventions are updated, *if needed*, 6 weeks after the Annual Meeting.
The need for an update is determined based on whether changes have passed through the approval process (e.g. been merged into the release branch in GitHub).
Exceptionally, updates can be released if needed for a particular project (as was the case for CMIP6 and CF-1.7).

// From DaL, integrate
The CF Governance Panel:

* Sets the terms of reference for committees and project teams involved in the governance of the CF Conventions;
* Convenes the Annual Meeting;
* Organises elections of the Committees and Panel;
* Arbitrates in the case of disagreements; and
* Guides the relationship of CF to other activities and representing the Conventions as an institution

The Panel can delegate any responsibility to an appropriate committee or ad-hoc project team as needed.

The CF Governance Panel is composed of a total of 5 members.

=== Constitution of the CF committees

Anyone with sufficient time, interest and expertise is qualified to serve as an ordinary member of the conventions committee or the standard names committee or both.
Prospective ordinary members will nominate themselves.
Committee members judged by the panel to have been inactive for an extended period will be asked to resign.
Members may choose to resign at any time and must retire after five years, but may be reappointed.

Each committee will elect its own chair from among its ordinary members whenever the position becomes vacant.
Whenever a vacancy arises subsequently, each committee will elect its own chair from among its ordinary members.
The chair may resign the office at any time and must retire after three years, but may be reelected.

Each committee will have authority and responsibility for the CF standard, as detailed in its terms of reference, having regard to the aims and general principles of design of CF.
It will discharge its responsibility by overseeing and contributing to public debate on how the standard should be expanded or altered, and by deciding after debate whether and what changes will be made.

Each committee will be assisted in its responsibility by a permanent and funded member of staff, who will be appointed in a manner decided by the CF Governance Panel, and who will be an ex-officio member and secretary of the committee.
The manager of CF conventions will be the secretary of the conventions committee and the manager of CF standard names will be the secretary of the standard names committee.
The committee will propose priorities for work by its secretary.

The committees may not devolve responsibility for the CF standard to other bodies, but they may encourage the formation of other permanent or temporary ad-hoc groups to debate issues and propose developments to CF.

Each committee will ensure that the parts of the standard for which it is responsible, any supporting documents and resources, and the procedures for proposing and deciding changes are kept up-to-date and made publicly available.

The committees may not change their constitutions or terms of reference themselves, but each may propose changes to be made by the CF Governance Panel.

The membership of the committee should include, but need not be limited to, representatives of those who maintain widely used software which follows the CF conventions, especially those which the committee regards as reference implementations, and representatives of the various scientific user communities of the CF standard.

=== Terms of reference of the conventions committee

The conventions committee will be responsible for the development of the CF conventions constituting the CF netCDF standard, except for the definition of standard names and of any other aspects of controlled vocabulary in the appendices to the standard that it agrees with the standard names committee should be within the remit of that committee.

The conventions committee and standard names committee will together define the format of the standard name table.

The conventions committee will have an interest in implementation of CF metadata conventions corresponding to the CF standard in other file formats and media apart from netCDF.

The conventions committee will be responsible for the CF conformance document and for deciding what CF conformance means.

The membership of the conventions committee should include representatives of those who maintain widely used software which follows the CF conventions, especially those which the committee regards as reference implementations.

// From DaL, integrate
The Conventions Committee:

* Identifies potentially needed changes to the CF Conventions;
* Moderates discussion of proposed changes to the CF Conventions; and
* Publishes new versions of the CF Conventions as needed.

The Conventions Committee is composed of a total of nine members.

=== Terms of reference of the standard names committee

The standard names committee will be responsible for the definition of CF standard names and of any other aspects of controlled vocabulary in the appendices to the CF netCDF standard that it agrees with the conventions committee should be within its remit.

The standard names committee will be responsible for maintaining the standard name table.
The standard names committee and the conventions committee will together define the format of the standard name table.

The standard names committee will have an interest in working towards interoperability with other vocabulary maintainers.

The committees will ensure that appropriate means are made available for making proposals and carrying out debates in a way which is visible and open to participation by all interested parties, and for retaining a permanent public record of debates and of any decisions made.

The committee will ensure that the standard, any supporting documents and resources, and the procedures for proposing and deciding changes are kept up-to-date and made publicly available.

// Migrated from Daniel's text
The release frequency and canonical source of the Standard Name Tables will be recorded.
Based off of historical evidence it seems realistic to plan monthly releases via GitHub.

// From DaL, integrate
The Standard Names Committee:

* Evaluates proposed standard names; and
* Publishes new versions of the Standard Names as needed.

The Standard Names Committee is composed of a total of nine members.

// Everything below here to EOF is from Daniel and to be integrated
== Ad-hoc project teams

Ad-hoc project teams can be created by the CF Governance Panel and any of the existing Committees.
They have a specific mandate and scope and are entrusted with completing specific tasks within a limited duration.
There are no limits on their size or membership.
After their defined duration has expired, a project team is dissolved.
If it has not been able to complete all of its tasks, a new ad-hoc project team can be created.

Examples for tasks that might be completed by an ad-hoc project team are:

* Migrating between technical platforms (e.g. Trac to GitHub);
* Upgrading the CF Checker;
* Setting up DOI usage in CF;
* Other tasks as needed.

== Community at large

The CF Conventions are designed to benefit their user community and the community at large is invited to contribute to the Conventions and the Standard Name Tables by participating in online discussions, attending meetings, proposing changes, or taking part in any other way they deem appropriate and useful.
Community members participate on a best effort basis and have no responsibility to fulfil.
