= CF Constitution

== Introduction

The CF Conventions' mission is to benefit of its users by enabling them to encode data products that are unambiguous, concise, understandable, and interoperable.
The CF Community embraces a philosophy of producing excellence by maintaining an open and welcoming culture and an environment that promotes debate and inquiry in a respectful, bold and intellectually rigorous fashion.
This is reflected in the community's https://github.com/cf-convention/cf-conventions/blob/master/CODE_OF_CONDUCT.md[Code of Conduct].

This constitution sets forth the mechanisms that are used in order to ensure that the Conventions can evolve in order to meet its users' needs.

== People involved in the CF governance process

The following groups are involved in the CF governance processes:

* CF Governance Panel
* Conventions Committee
* Standard Name Committee

The following sections describe the specific roles of people in these groups.

The officers in each group are:

* A chair, responsible for chairing meetings and communicating on the group's behalf;
* A secretary, responsible for ensuring that meetings are properly minuted, maintaining the documents the group is responsible for, and ensuring that formal rules are adhered to; and
* Other members who contribute to the work of the group.
This may include officers who are appointed by the group in order to have responsibility for specific tasks.

All bodies involved in the CF governance process carry out debates and make decisions in a way that is visible and transparent to all interested parties.
They maintain permanent, public records of these items and all versions of all documents they are responsible for.

In addition, the following groups exist or can be created as needed in order to support the progress and evolutions of the CF Conventions:

* Project teams
* Community at large

These groups do not have officers and have no commitment to maintain records.

== Composition of groups involved in CF governance

Each year, at the Annual Meeting, the term of the longest serving member in the Governance Panel and each Committee ends.
The Governance Panel can appoint volunteers to positions in the Governance Panel and any Committee at any time.
Likewise, a member of any group may resign at any time.
A member can volunteer for membership in any group as many times as they like.

The Chair of each group is elected by vote within the group at the Annual Meeting.
Membership in one group does not preclude membership in others.

Any group member can delegate their duties to a qualified delegate.

Project teams can be appointed from volunteers by the CF Governance Panel and any Committee.
Membership in a project team expires when the member resigns or the project team is dissolved.

Contributions to any group involved in the CF governance process are tracked in a dedicated document by the secretary of the relevant group.
Project teams fall in the responsibility of the group that created them.

=== Roles and responsibilities

==== The CF Governance Panel

The Governance Panel promotes the use of CF within the community of users who make use of or could profit from using the CF Conventions.
It has no special responsibility for or influence on the technical content of the CF Conventions or Standard Name Table.

Its duties include:

* organising an Annual Meeting for discussing issues relevant to the CF Conventions;
* encouraging support of CF by benevolent organisations;
* exploring funding mechanisms for CF activities;
* representing CF to other organisations;
* appointing volunteers to the various groups involved in CF governance that have the expertise and interests relevant to their work in those bodies;
* encouraging representation of different communities and geographic regions within the governance bodies in its purview;
* publishing the Constitution;
* maintaining public lists of the members of all groups involved in CF governance.

==== The Conventions Committee

The Conventions Committee develops and maintains the CF Conventions on behalf of the user community.
It ensures that the CF Conventions evolve in line with the mission and philosophy of CF and the needs of the user community.
It also ensures that the Conventions remain coherent, implementable, and verifiable.

Its duties include:

* moderating and contributing to discussions of proposed changes to the CF Conventions;
* approving or rejecting proposed changes to the CF Conventions;
* publishing new versions of the CF Conventions.

===== Moderating proposals to change the CF Conventions

Anyone who has an idea of how to improve the CF Conventions can propose a change as outlined in https://github.com/cf-convention/cf-conventions/blob/master/CONTRIBUTING.md[the contribution guidelines].
Once such a proposal has been made, a moderator of the ensuing discussion is sought from the Conventions Committee.

The moderator has the duty to

* ensure that the discussion surrounding the proposal is in line with the CF Community's philosophy and https://github.com/cf-convention/cf-conventions/blob/master/CODE_OF_CONDUCT.md[Code of Conduct];
* invite relevant experts to take part in the discussion;
* summarise the ongoing discussion periodically;
* manage the voting process to accept or reject the proposal when a motion is raised to adopt the proposal's text.

===== Approving or rejecting proposed changes to the CF Conventions

When a member of the CF community feels that a proposed change has been sufficiently discussed and refined, they may make a motion to adopt it.
If this motion is seconded by a member of the Conventions Committee, others within the community have three weeks to voice concerns against its adoption.
If after three weeks no concerns have been voiced, the motion qualifies as approved and is accepted for publishing in the next release of hte Conventions.
If objections are voiced, at the end of the three weeks a vote is held on whether to accept the proposal.
The proposal is then accepted or rejected based on simple majority.

===== Publishing new versions of the CF Conventions

The CF Conventions are updated, if changes have been accepted, at the conclusion of the Annual Meeting.
Exceptionally, updates can be released acyclically if there is a pressing need.

==== The Standard Names Committee

The Standard Names Committee defines CF standard names and maintains controlled vocabulary in the appendices to the CF Conventions.
It pursues pursues interoperability with other controlled vocabularies and ontologies.
Its duties include:

* maintaining the contents and format of the standard name table;
* evaluating proposed standard names;
* publishing new versions of the standard names table as needed.

==== Project teams

Project teams can be created by the CF Governance Panel and any of the existing Committees.
They have a specific mandate and scope and are entrusted with completing specific tasks within a limited duration.
There are no limits on their size or membership.
After their defined duration has expired, a project team is dissolved.
If it has not been able to complete all of its tasks, a new project team can be created.

Examples for tasks that might be completed by an project team are:

* migrating between technical platforms (e.g. Trac to GitHub);
* upgrading the CF Checker;
* setting up DOI usage in CF;
* other tasks as needed.

==== Community at large

The CF Conventions are designed to benefit their user community and the community at large is invited to contribute to the Conventions and the Standard Name Tables by participating in online discussions, attending meetings, proposing changes, or taking part in any other way they deem appropriate and useful.
Community members participate on a best effort basis and have no responsibility to fulfil.
