= CF Constitution

// TODOs
// Add: What bodies exist? How do they interact? What are their duties? What other things are there to do?
// What are the "responsibilities/duties" of the different stakeholders?
// How do we ensure that there is a moderator who processes a ticket?
// Move tenses: None of this "will be", etc. - this is *what we do now*.
// Possible sections to add: a) Meetings and releases; b) Roles and responsibilities
////
Stuff we know we want to implement in CONTRIBUTING.md
Streamline moderation process by:
1. Replace the moderator of discussions on GitHub (currently a "member of the conventions committee, or another suitably qualified person") with a member of the of the Conventions Committee or a volunteer whom they have selected. 
2. Replace the mandatory 3 week period of silence between the beginning of discussion on GitHub and the summary of the proposal's discussion by a 5 week discussion period with no mandatory silence.
This period can be extended if necessary.
3. Replace the mandatory 3 week period of silence after the moderator summarises the state of discussion by a 1 week period that can be extended if necessary.

Also needed in this document are stuff about moderator's role, etc. and how to assign people
////

== Introduction

The CF Conventions' mission is to benefit of its users by enabling them to encode data products that are unambiguous, concise, understandable, and interoperable.
The CF Community embraces a philosophy of producing excellence by maintaining an open and welcoming culture and an environment that promotes debate and inquiry in a respectful, bold and intellectually rigorous fashion.
This is reflected in the community's https://github.com/cf-convention/cf-conventions/blob/master/CODE_OF_CONDUCT.md[Code of Conduct].

This constitution sets forth the mechanisms that are used in order to ensure that the Conventions can evolve in order to meet its users' needs.

== People involved in the CF governance process

The following groups are involved in the CF governance processes:

* CF Governance Panel
* Conventions Committee
* Standard Name Committee
* Project teams
* Community at large

The following sections describe the specific roles of people in these groups.

The officers in each group are:

* A chair, responsible for chairing meetings and communicating on the group's behalf;
* A secretary, responsible for ensuring that meetings are properly minuted, maintaining the documents the group is responsible for, and ensuring that formal rules are adhered to; and
* Other members who contribute to the work of the group.
This may include officers who are appointed by the group in order to have responsibility for specific tasks.

== Composition of groups involved in CF governance

Each year, at the Annual Meeting, the term of the longest serving member in the Governance Panel and each Committee ends.
The Governance Panel can appoint volunteers to positions in the Governance Panel and any Committee at any time.
Likewise, a member of any group may resign at any time.
A member can volunteer for membership in any group as many times as they like.

The Chair, Secretary, and all officers within each group are elected by vote within the group at the Annual Meeting.
Membership in one group does not preclude membership in others.

Any group member can delegate their duties to a qualified delegate.

Project teams can be appointed from volunteers by the CF Governance Panel and any Committee.
Membership in a project team expires when the member resigns or the project team is dissolved.

Contributions to any group involved in the CF governance process are tracked in a dedicated document by the secretary of the relevant group.
Project teams fall in the responsibility of the secretary of the group that created them.

=== Roles and responsibilities

==== The CF Governance Panel

The Governance Panel promotes the use of CF within the community of users who make use of or could profit from using the CF Conventions.
It has no special responsibility for or influence on the technical content of the CF Conventions or Standard Name Table.

Its duties include:

* organising an Annual Meeting for discussing issues relevant to the CF Conventions;
* encouraging support of CF by benevolent organisations;
* exploring funding mechanisms for CF activities;
* representing CF to other organisations;
* appointing volunteers to the various groups involved in CF governance that have the expertise and interests relevant to their work in those bodies;
* encouraging representation of different communities and geographic regions within the governance bodies in its purview;
* publishing the Constitution;
* maintaining public lists of the members of all groups involved in CF governance.

==== The Conventions Committee

The Conventions Committee is develops and maintains the CF Conventions on behalf of the user community.
It ensures that the CF Conventions evolve in line with the mission and philosophy of CF and the needs of the user community
It also ensures that the Conventions remain coherent, implementable, and verifiable.

Its duties include:

* moderating and contributing to discussions of proposed changes to the CF Conventions;
* approving or rejecting proposed changes to the CF Conventions;
* publishing new versions of the CF Conventions.

===== Moderating proposals to change the CF Conventions

Anyone who has an idea of how to improve the CF Conventions can propose a change as outlined in https://github.com/cf-convention/cf-conventions/blob/master/CONTRIBUTING.md[the contribution guidelines].
Once such a proposal has been made, a moderator of the ensuing discussion is sought from the Conventions Committee.

The moderator has the duty to

* ensure that the discussion surrounding the proposal is in line with the CF Community's philosophy and https://github.com/cf-convention/cf-conventions/blob/master/CODE_OF_CONDUCT.md[Code of Conduct];
* invite relevant experts to take part in the discussion;
* summarise the ongoing discussion periodically;
* manage the voting process to accept or reject the proposal when a motion is raised to adopt the proposal's text.

===== Publishing new versions of the CF Conventions

The CF Conventions are updated, if outstanding changes have been accepted, following the Annual Meeting.
Exceptionally, updates can be released acyclically if there is a pressing need.

// TODO: Finish below here
=== Terms of reference of the standard names committee

The standard names committee will be responsible for the definition of CF standard names and of any other aspects of controlled vocabulary in the appendices to the CF netCDF standard that it agrees with the conventions committee should be within its remit.

The standard names committee will be responsible for maintaining the standard name table.
The standard names committee and the conventions committee will together define the format of the standard name table.

The standard names committee will have an interest in working towards interoperability with other vocabulary maintainers.

The committees will ensure that appropriate means are made available for making proposals and carrying out debates in a way which is visible and open to participation by all interested parties, and for retaining a permanent public record of debates and of any decisions made.

The committee will ensure that the standard, any supporting documents and resources, and the procedures for proposing and deciding changes are kept up-to-date and made publicly available.

// Migrated from Daniel's text
The release frequency and canonical source of the Standard Name Tables will be recorded.
Based off of historical evidence it seems realistic to plan monthly releases via GitHub.

// From DaL, integrate
The Standard Names Committee:

* Evaluates proposed standard names; and
* Publishes new versions of the Standard Names as needed.

The Standard Names Committee is composed of a total of nine members.

// Everything below here to EOF is from Daniel and to be integrated
== Project teams

Project teams can be created by the CF Governance Panel and any of the existing Committees.
They have a specific mandate and scope and are entrusted with completing specific tasks within a limited duration.
There are no limits on their size or membership.
After their defined duration has expired, a project team is dissolved.
If it has not been able to complete all of its tasks, a new project team can be created.

Examples for tasks that might be completed by an project team are:

* Migrating between technical platforms (e.g. Trac to GitHub);
* Upgrading the CF Checker;
* Setting up DOI usage in CF;
* Other tasks as needed.

== Community at large

The CF Conventions are designed to benefit their user community and the community at large is invited to contribute to the Conventions and the Standard Name Tables by participating in online discussions, attending meetings, proposing changes, or taking part in any other way they deem appropriate and useful.
Community members participate on a best effort basis and have no responsibility to fulfil.
