= Terms of Reference for CF Committees and Governance Panel
B. N. Lawrence, R. Drach, B. E. Eaton, J. M. Gregory, S. C. Hankin, R. K. Lowry, R. K. Rew, and K. E. Taylor
From the CF white paper of 2006, Appendix Two: Terms of Reference for Committees and Governance Panel

== Introduction

The CF Conventions are designed for the benefit of its users.
This constitution sets forth the mechanisms that are used in order to ensure that the Conventions can evolve in order to meet its users' needs.

=== Constitution of the CF Governance Panel

The CF Governance Panel governs the development and maintenance of the CF standard on behalf of the user community, under the auspices of the WMO/WCRP Working Group on Coupled Modelling (WGCM).
If the WGCM wishes to transfer or share responsibility for CF with another permanent committee of an international organisation, it may decide to do so with the agreement of the CF Governance Panel and the CF committee.

The panel will include, but not be limited to, members of the WGCM, the leaders, or their nominees, of organisations contributing significant resources in support of CF, and the chairs of the CF committees on conventions and standard names.

=== Terms of reference of the CF Governance Panel

The panel will be responsible for the stewardship of CF, but will not have any special responsibility for or influence on the technical content of CF.

The panel will ensure that its own constitution and terms of reference, those of the CF committees, and the aims and general principles of design of the CF standard are published.
These may be altered by the panel only after appropriate public debate and with the agreement of both CF committees.

The panel will promote and help integrate the use of CF across WCRP programmes, the broader programmes of WCRP's sponsors (ICSU, WMO, and IOC), and other interested communities.
In particular the panel will attempt to influence developing metadata standards of WMO and other international organisations so that they accommodate the CF standard.

The panel will encourage continued support of CF by benevolent organisations and explore additional funding mechanisms if necessary.

The panel will appoint people who have nominated themselves or agreed to serve as members of the conventions committee and the standard names committee.
In doing so it will have regard to the expertise and interests relevant to the remit of each committee and will attempt to obtain representation of a variety of communities and a geographical spread of members.
The maximum and minimum numbers of members of either committee is decided by agreement between that committee and the panel.
The panel will ensure that the current membership of the two CF committees is published.

The panel will convene an annual meeting of the CF community.

=== Constitution of the CF committees

Anyone with sufficient time, interest and expertise is qualified to serve as an ordinary member of the conventions committee or the standard names committee or both.
Prospective ordinary members will nominate themselves.
Committee members judged by the panel to have been inactive for an extended period will be asked to resign.
Members may choose to resign at any time and must retire after five years, but may be reappointed.

Each committee will elect its own chair from among its ordinary members whenever the position becomes vacant.
Whenever a vacancy arises subsequently, each committee will elect its own chair from among its ordinary members.
The chair may resign the office at any time and must retire after three years, but may be reelected.

Each committee will have authority and responsibility for the CF standard, as detailed in its terms of reference, having regard to the aims and general principles of design of CF.
It will discharge its responsibility by overseeing and contributing to public debate on how the standard should be expanded or altered, and by deciding after debate whether and what changes will be made.

Each committee will be assisted in its responsibility by a permanent and funded member of staff, who will be appointed in a manner decided by the CF Governance Panel, and who will be an ex-officio member and secretary of the committee.
The manager of CF conventions will be the secretary of the conventions committee and the manager of CF standard names will be the secretary of the standard names committee.
The committee will propose priorities for work by its secretary.

The committees may not devolve responsibility for the CF standard to other bodies, but they may encourage the formation of other permanent or temporary ad-hoc groups to debate issues and propose developments to CF.

Each committee will ensure that the parts of the standard for which it is responsible, any supporting documents and resources, and the procedures for proposing and deciding changes are kept up-to-date and made publicly available.

The committees may not change their constitutions or terms of reference themselves, but each may propose changes to be made by the CF Governance Panel.

The membership of the committee should include, but need not be limited to, representatives of those who maintain widely used software which follows the CF conventions, especially those which the committee regards as reference implementations, and representatives of the various scientific user communities of the CF standard.

=== Terms of reference of the conventions committee

The conventions committee will be responsible for the development of the CF conventions constituting the CF netCDF standard, except for the definition of standard names and of any other aspects of controlled vocabulary in the appendices to the standard that it agrees with the standard names committee should be within the remit of that committee.

The conventions committee and standard names committee will together define the format of the standard name table.

The conventions committee will have an interest in implementation of CF metadata conventions corresponding to the CF standard in other file formats and media apart from netCDF.

The conventions committee will be responsible for the CF conformance document and for deciding what CF conformance means.

The membership of the conventions committee should include representatives of those who maintain widely used software which follows the CF conventions, especially those which the committee regards as reference implementations.

=== Terms of reference of the standard names committee

The standard names committee will be responsible for the definition of CF standard names and of any other aspects of controlled vocabulary in the appendices to the CF netCDF standard that it agrees with the conventions committee should be within its remit.

The standard names committee will be responsible for maintaining the standard name table.
The standard names committee and the conventions committee will together define the format of the standard name table.

The standard names committee will have an interest in working towards interoperability with other vocabulary maintainers.

The committees will ensure that appropriate means are made available for making proposals and carrying out debates in a way which is visible and open to participation by all interested parties, and for retaining a permanent public record of debates and of any decisions made.

The committee will ensure that the standard, any supporting documents and resources, and the procedures for proposing and deciding changes are kept up-to-date and made publicly available.
