[[revhistory, Revision History]]
== Revision History

.14 June 2004
. Added <<lambert-azimuthal-equal-area,the section called “Lambert azimuthal equal area”>>.
. <<polar-stereographic,the section called "Polar Stereographic">> : Added **`latitude_of_projection_origin`** map parameter.

.1 July 2004
. <<scalar-coordinate-variables>> : Added note that use of scalar coordinate variables inhibits interoperability with COARDS conforming applications.
. <<multiple-forecasts-from-single-analysis>> : Added **`positive`** attribute to the scalar coordinate p500 to make it unambiguous that the pressure is a vertical coordinate value.

.20 September 2004
. <<cell-methods>> : Changed several incorrect occurances of the cell method **`"standard deviation"`** to **`"standard_deviation"`**.

.22 October 2004
. Added <<lambert-conformal-projection>>.

.25 November 2005
. <<atmosphere-hybrid-height-coordinate,the section called "Atmosphere hybrid height coordinate">> : Fixed definition of atmosphere hybrid height coordinate.

.21 March 2006
. Added <<azimuthal-equidistant,the section called "Azimuthal equidistant">>.
. Added <<atmosphere-natural-log-pressure-coordinate,the section called "Atmosphere natural log pressure coordinate">>.

.17 January 2008
. <<preface>> : Changed text to refer to rules of CF governance, and provisional status.
. <<coordinate-types>> , <<coordinate-system>> : Made changes regarding use of the axis attribute to identify horizontal coordinate variables.
. Changed document version to 1.1.

.4 May 2008
. <<grid-mappings-and-projections>>, <<appendix-grid-mappings>> : Additions and revisions to CF grid mapping attributes to support the specification of coordinate reference system properties link:$$http://cf-trac.llnl.gov/trac/ticket/18$$[(Trac ticket #18)].
. <<table-supported-units,Table 3.1, "Supported Units">> : Corrected Prefix for Factor "1e-2" from "deci" to "centi". link:$$http://cf-trac.llnl.gov/trac/ticket/25$$[(Trac ticket #25)].
. Changed document version to 1.2.

.15 July 2008
. <<flags>> , <<attribute-appendix>> , <<standard-name-modifiers>> : Enhanced the Flags definition to support bit field notation using a **`flag_masks`** attribute. link:$$http://cf-trac.llnl.gov/trac/ticket/26$$[(Trac ticket #26)].
. Changed document version to 1.3.

.9 October 2008
. Fixed defect in <<atm-sigma-coord-ex,Example 4.3, “Atmosphere sigma coordinate”>>. link:$$http://cf-trac.llnl.gov/trac/ticket/30$$[(Trac ticket #30)].
. Fixed defect in <<coordinate-system>>. link:$$http://cf-trac.llnl.gov/trac/ticket/32$$[(Trac ticket #32)].

.7 November 2008
. Fixed defect in wording of <<coordinate-system>>. link:$$http://cf-trac.llnl.gov/trac/ticket/35$$[(Trac ticket #35)].
. Fixed defect related to subsection headings in <<dimensionless-v-coord>>. link:$$http://cf-trac.llnl.gov/trac/ticket/36$$[(Trac ticket #36)].

.10 December 2008
. Changes related to removing ambiguity in <<cell-methods>>. link:$$http://cf-trac.llnl.gov/trac/ticket/17$$[(Trac ticket #17)].
. Changed document version to 1.4.

.11 December 2008
. Added grid mappings Lambert Cylindrical Equal Area, Mercator, and Orthographic to <<appendix-grid-mappings>>. link:$$http://cf-trac.llnl.gov/trac/ticket/34$$[(Trac ticket #34)].

.12 December 2008
. Fixed defect in Mercator section of <<appendix-grid-mappings>> by updating to version 12 of Grid Map Names (see link:$$http://cf-trac.llnl.gov/trac/wiki/GridMapNames?version=12$$[]).

.27 February 2009
. Fixed defect by clarifying that coordinates indicate gridpoint location in <<coordinate-types>>. link:$$http://cf-trac.llnl.gov/trac/ticket/44$$[(Trac ticket #44)].
. Fixed defect of outdated Conventions attribute. link:$$http://cf-trac.llnl.gov/trac/ticket/45$$[(Trac ticket #45)].

.25 October 2010
Minor revisions requested by Jonathan Gregory.
Revisions 33 and 49 were closed after discussions; the rest had elicited no objections.

. Ticket 33, cell_methods for statistical indices
. Ticket 49, clarification of flag_meanings attribute
. Ticket 58, remove deprecation of "missing_value" attribute

. Ticket 57, fix for broken URLs in CF Conventions document
. Ticket 56, typo in CF conventions doc
. Ticket 51, syntax consistency for dimensionless vertical coordinate definitions
. Ticket 47, error in example 7.4
. Changed document version to 1.5.
. New chapter, ticket 37 Changed document version to 1.6.

.22 June 2011
Ticket 37. Added Chapter 9, Discrete Sampling Geometries, and a related Appendix H, and revised several other chapters.

.5 December 2011
In Appendix H (Annotated Examples of Descrete Geometries), updated standard names "station_description" and "station_wmo_id" to "platform_name" and "platform_id".

.23 December 2015
Re-do several changes which had previously been made in an earlier draft of version 1.7:

. Ticket 61, two new cell methods in Appendix E.
. Ticket 64, section 7.3 editorial correction, replace "cell_bounds" with "bounds".
. Ticket 65, add range entry in Appendix E.
. Ticket 69. Added Section 5.6.1, Use of the CRS Well-known Text Format and related changes.
. Ticket 93, Added two new dimensionless coordinates to Appendix D.

.20 January 2016
. link:$$http://cf-trac.llnl.gov/trac/ticket/67$$[Ticket 67], remove
deprecation of "missing_value" from <<attribute-appendix>>.
. link:$$http://cf-trac.llnl.gov/trac/ticket/71$$[Ticket #71], correction of <<vertical-perspective>> projection.

.29 February 2016
. link:$$http://cf-trac.llnl.gov/trac/ticket/103$$[Ticket 103] updated Type and Use values for some attributes in <<attribute-appendix>> and added "special purpose" value. In <<appendix-examples-discrete-geometries>>, updated coordinate values for the variables in some examples to correct omissions.

.30 March 2016
. link:$$http://cf-trac.llnl.gov/trac/ticket/141$$[Ticket 141], update
affiliation organisations for Jonathan Gregory and Phil Bentley.

.27 July 2016
. link:$$http://cf-trac.llnl.gov/trac/ticket/31$$[Ticket 31],
add new attribute **`actual_range`**.

.7 February 2017
. renamed Appendix G to Revision History, as in Trac Ticket 73.
. revised section 3.3 for Trac ticket 123.

.14 February 2017
. Ticket #118, Add geoid_name and geopotential_datum_name to the list of
Grid Mapping Attributes.
. Ticket #148, Added maximum_absolute_value, minimum_absolute_value and
mean_absolute_value to cell methods in Appendix E
. Ticket #149, correction of standard name in example 7.3

.15 February 2017
. Ticket #77, Add sinusoidal projection
. Ticket #87, Allow comments in coordinate variables
. Ticket #92, Add oblique mercator projection
. Ticket #72, Adding the geostationary projection.

.16 February 2017
. Ticket #103, Corrections to Appendices A and H, finish the ticket with remaining changes to Appendix H.

.21 February 2017 
. Ticket #74, Removed "sea_water_speed" from flag values example and added Note at 
bottom of Example 3.3 in Chapter 3.  Also added a sentence to Appendix C Standard Name 
Modifiers "number of observations" and and a sentence to "status_flag_modifiers"

.7 March 2017
. Ticket #145, Add new sentence to bottom of Section 7.2, Add new Section 2.6.3, "External variables", 
Add "External variable" attribute to Appendix A.

.08 March 2017
. Ticket #85, Added sentence to bottom of first para in Section 9.1 "Features and feature types".  Added Links column in Section 9.1
Replaced first para in Section 9.6. "Missing Data". Added verbiage to Section 2.5.1, "Missing data...".  Added sentence to Appendix A 
"Description" "missing_value" and "Fill_Value".
. Ticket #143, Supplement the definitions of dimensionless vertical coordinates

.09 March 2017
. Ticket #75, fix documentation and definitions of 3 grid mapping definitions

.23 March 2017
. Ticket #109, resolve inconsistency of positive and standard_name attributes (section 4.3)
. Ticket #76, More than one name in Conventions attribute (section 2.6.1)
. Ticket #138, Clarification of false_easting / false_northing (Table F.1)
. Ticket #86, Allow coordinate variables to be scaled integers, affects two table rows in Appendix A.

.27 March 2017
. Ticket #80, added attributes to AppF Table F1, changes in section 5.6 and 5.6.1.

.28 March 2017
. Ticket #102, additional cell_methods, changes in Appendix E and section 7.3
. Ticket #104, Clarify the interpretation of scalar coordinate variables, changes in sections 5.7 and 6.1

.06 April 2017
. Ticket #70, Connecting coordinates to Grid Mapping variables: revisions in Section 5.6 and Examples 5.10 and 5.12

.25 April 2017
. Ticket #100, Clarifications to the preamble of sections 4 and 5.

.29 June 2017
. Ticket #140, Added 3 paragraphs and an example to Chapter 7, Section 7.1.

.18 July 2017
. a few formatting tweaks
. Where appropriate, changed document version from 1.6 to 1.7, and 1.7 (DRAFT) to 1.7.

.1 August 2017
. Updated the links and references to NUG (The NetCDF User Guide), to refer to the current version.
. Trivial updates to links for COARDS and UDUNITS in the bibliography.

.10 August 2017
. Updated use of WKT-CRS syntax.

.17 October 2017
. Ticket #164, New Geometries section 7.5.

.13 December 2017
. Ticket #164, Implement suggestions from trac ticket comments.

.24 January 2018
. Ticket #164, If coordinates attribute is carried by geometry container, require coordinate variables which correspond to node coordinate variables to have the corresponding axis attribute.

.24 January 2018
. Ticket #164, Remove geometry attribute from lat/lon variables in examples. 

.20 April 2018
. Ticket #164, Add Tim Whiteaker and Dave Blodgett as authors.

.09 May 2018
. Ticket #164, Replace axis with bounds for coordinate variables related to geometry node variables.

.25 June 2018
. Ticket #164, Add bounds attribute to first geometry CDL example.
